Dane do analizy: https://www.kaggle.com/datasets/faizunnabi/autism-screening

In [ ]:
#!/bin/bash
!kaggle datasets download faizunnabi/autism-screening

Dataset URL: https://www.kaggle.com/datasets/faizunnabi/autism-screening
License(s): CC0-1.0
Downloading autism-screening.zip to /content
  0% 0.00/7.34k [00:00<?, ?B/s]
100% 7.34k/7.34k [00:00<00:00, 9.78MB/s]

In [ ]:
!unzip autism-screening.zip

Archive:  autism-screening.zip
  inflating: Autism_Data.arff

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# to convert ? as NaN
df = pd.read_csv("Autism_Data.arff", na_values=['?'])
df.head()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,'United States',no,6,'18 and more',Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5,'18 and more',Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8,'18 and more',Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,'United States',no,6,'18 and more',Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,NaN,no,no,Egypt,no,2,'18 and more',NaN,NO

In [ ]:
df.describe()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,result
count,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,704.000000,702.000000,704.000000
mean,0.721591,0.453125,0.457386,0.495739,0.498580,0.284091,0.417614,0.649148,0.323864,0.573864,29.698006,4.875000
std,0.448535,0.498152,0.498535,0.500337,0.500353,0.451301,0.493516,0.477576,0.468281,0.494866,16.507465,2.501493
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000,3.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,27.000000,4.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,35.000000,7.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,383.000000,10.000000

In [ ]:
df.shape

(704, 21)

In [ ]:
df.isnull().sum()

A1_Score            0
A2_Score            0
A3_Score            0
A4_Score            0
A5_Score            0
A6_Score            0
A7_Score            0
A8_Score            0
A9_Score            0
A10_Score           0
age                 2
gender              0
ethnicity          95
jundice             0
austim              0
contry_of_res       0
used_app_before     0
result              0
age_desc            0
relation           95
Class/ASD           0
dtype: int64

In [ ]:
df['ethnicity'].value_counts()

ethnicity
White-European       233
Asian                123
'Middle Eastern '     92
Black                 43
'South Asian'         36
Others                30
Latino                20
Hispanic              13
Pasifika              12
Turkish                6
others                 1
Name: count, dtype: int64

In [ ]:
pd.get_dummies(df, dummy_na=True).isnull().sum()

A1_Score         0
A2_Score         0
A3_Score         0
A4_Score         0
A5_Score         0
                ..
relation_Self    0
relation_nan     0
Class/ASD_NO     0
Class/ASD_YES    0
Class/ASD_nan    0
Length: 115, dtype: int64

In [ ]:
df

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,'United States',no,6,'18 and more',Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5,'18 and more',Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8,'18 and more',Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,'United States',no,6,'18 and more',Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,NaN,no,no,Egypt,no,2,'18 and more',NaN,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,...,f,White-European,no,no,Russia,no,7,'18 and more',Self,YES
700,1,0,0,0,0,0,0,1,0,1,...,m,Hispanic,no,no,Mexico,no,3,'18 and more',Parent,NO
701,1,0,1,1,1,0,1,1,0,1,...,f,NaN,no,no,Russia,no,7,'18 and more',NaN,YES
702,1,0,0,1,1,0,1,0,1,1,...,m,'South Asian',no,no,Pakistan,no,6,'18 and more',Self,NO
703,1,0,1,1,1,0,1,1,1,1,...,f,White-European,no,no,Cyprus,no,8,'18 and more',Self,YES

In [ ]:
df = df.drop(columns=['ethnicity', 'relation'])

In [ ]:
df = df.drop(columns=['contry_of_res',	'used_app_before',	'age_desc',	'Class/ASD', 'result'], errors='ignore')

In [ ]:
df = df[df['age'] < 200]

In [ ]:
df.isnull().sum().sum()

0

In [ ]:
df = pd.get_dummies(df, drop_first=True)
df

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender_m,jundice_yes,austim_yes
0,1,1,1,1,0,0,1,1,0,0,26.0,False,False,False
1,1,1,0,1,0,0,0,1,0,1,24.0,True,False,True
2,1,1,0,1,1,0,1,1,1,1,27.0,True,True,True
3,1,1,0,1,0,0,1,1,0,1,35.0,False,False,True
4,1,0,0,0,0,0,0,1,0,0,40.0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,0,1,0,1,1,0,1,1,1,1,25.0,False,False,False
700,1,0,0,0,0,0,0,1,0,1,34.0,True,False,False
701,1,0,1,1,1,0,1,1,0,1,24.0,False,False,False
702,1,0,0,1,1,0,1,0,1,1,35.0,True,False,False
703,1,0,1,1,1,0,1,1,1,1,26.0,False,False,False

## Standaryzacja danych (zadanie)

In [ ]:
df_dummy = df

In [ ]:
X, y = df_dummy.drop(columns=['austim_yes']), df_dummy['austim_yes']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=402)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit(X_train)  #  ważne skalujemy tylko na zbiorze traninigowym

In [ ]:
X_train  = df_scaled.transform(X_train)
X_test = df_scaled.transform(X_test)

In [ ]:
from sklearn import neighbors

In [ ]:
knn = neighbors.KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.score(X_test, y_test), knn.score(X_train, y_train)

(0.8578199052132701, 0.8775510204081632)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, knn.predict(X_test))

array([[175,   9],
       [ 21,   6]])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test, knn.predict(X_test)))

              precision    recall  f1-score   support

       False       0.89      0.95      0.92       184
        True       0.40      0.22      0.29        27

    accuracy                           0.86       211
   macro avg       0.65      0.59      0.60       211
weighted avg       0.83      0.86      0.84       211

In [ ]:
print(classification_report(y_train, knn.predict(X_train)))

              precision    recall  f1-score   support

       False       0.89      0.98      0.93       426
        True       0.58      0.22      0.32        64

    accuracy                           0.88       490
   macro avg       0.74      0.60      0.63       490
weighted avg       0.85      0.88      0.85       490

# Model: random forest

In [ ]:
from sklearn import ensemble
rfc = ensemble.RandomForestClassifier()

In [ ]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
print(classification_report(y_test, rfc.predict(X_test)))

              precision    recall  f1-score   support

       False       0.90      0.98      0.94       184
        True       0.67      0.22      0.33        27

    accuracy                           0.89       211
   macro avg       0.78      0.60      0.64       211
weighted avg       0.87      0.89      0.86       211

# Model logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression(random_state=0, C=2)

In [ ]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)

In [ ]:
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00       184
        True       1.00      1.00      1.00        27

    accuracy                           1.00       211
   macro avg       1.00      1.00      1.00       211
weighted avg       1.00      1.00      1.00       211

# Model tree

In [ ]:
from sklearn import tree
clf_tree = tree.DecisionTreeClassifier(max_depth=7)  #  max_depth to jest przykład hiper parametru
clf_tree.fit(X_train, y_train)
print(classification_report(y_test, clf_tree.predict(X_test)))

              precision    recall  f1-score   support

       False       0.88      0.91      0.90       184
        True       0.24      0.19      0.21        27

    accuracy                           0.82       211
   macro avg       0.56      0.55      0.55       211
weighted avg       0.80      0.82      0.81       211

In [ ]:
print(classification_report(y_train, clf_tree.predict(X_train)))

              precision    recall  f1-score   support

       False       0.93      0.98      0.96       426
        True       0.82      0.52      0.63        64

    accuracy                           0.92       490
   macro avg       0.88      0.75      0.80       490
weighted avg       0.92      0.92      0.91       490

# Zmiana podejścia

In [ ]:
# to convert ? as NaN
df = pd.read_csv("Autism_Data.arff", na_values=['?'])
df.head()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,gender,ethnicity,jundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,1,1,0,0,1,1,0,0,...,f,White-European,no,no,'United States',no,6,'18 and more',Self,NO
1,1,1,0,1,0,0,0,1,0,1,...,m,Latino,no,yes,Brazil,no,5,'18 and more',Self,NO
2,1,1,0,1,1,0,1,1,1,1,...,m,Latino,yes,yes,Spain,no,8,'18 and more',Parent,YES
3,1,1,0,1,0,0,1,1,0,1,...,f,White-European,no,yes,'United States',no,6,'18 and more',Self,NO
4,1,0,0,0,0,0,0,1,0,0,...,f,NaN,no,no,Egypt,no,2,'18 and more',NaN,NO

In [ ]:
df_2 = df.copy()

In [ ]:
df_2.columns

Index(['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender',
       'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before',
       'result', 'age_desc', 'relation', 'Class/ASD'],
      dtype='object')

In [ ]:
df_dummy = df_2.drop(columns=['result', 'Class/ASD'])

In [ ]:
df_dummy.columns

Index(['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age', 'gender',
       'ethnicity', 'jundice', 'austim', 'contry_of_res', 'used_app_before',
       'age_desc', 'relation'],
      dtype='object')

In [ ]:
df['austim'].value_counts()

austim
no     613
yes     91
Name: count, dtype: int64

In [ ]:
df_dummy = pd.get_dummies(df_dummy, dummy_na=True) + 0

In [ ]:
df_dummy.head()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,used_app_before_yes,used_app_before_nan,age_desc_'18 and more',age_desc_nan,relation_'Health care professional',relation_Others,relation_Parent,relation_Relative,relation_Self,relation_nan
0,1,1,1,1,0,0,1,1,0,0,...,0,0,1,0,0,0,0,0,1,0
1,1,1,0,1,0,0,0,1,0,1,...,0,0,1,0,0,0,0,0,1,0
2,1,1,0,1,1,0,1,1,1,1,...,0,0,1,0,0,0,1,0,0,0
3,1,1,0,1,0,0,1,1,0,1,...,0,0,1,0,0,0,0,0,1,0
4,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
df_dummy[['austim_yes', 'austim_no', 'austim_nan']]

     austim_yes  austim_no  austim_nan
0             0          1           0
1             1          0           0
2             1          0           0
3             1          0           0
4             0          1           0
..          ...        ...         ...
699           0          1           0
700           0          1           0
701           0          1           0
702           0          1           0
703           0          1           0

[704 rows x 3 columns]

In [ ]:
[col for col in df_dummy.columns if 'aus' in col]

['austim_no', 'austim_yes', 'austim_nan']

In [ ]:
df_dummy.corr()['']

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,used_app_before_yes,used_app_before_nan,age_desc_'18 and more',age_desc_nan,relation_'Health care professional',relation_Others,relation_Parent,relation_Relative,relation_Self,relation_nan
A1_Score,1.000000,0.011539,0.074096,0.127814,0.169369,0.110199,0.217538,0.147640,0.145452,0.118413,...,-0.040620,NaN,NaN,NaN,0.004791,-0.022944,-0.000981,-0.003317,0.089246,-0.107144
A2_Score,0.011539,1.000000,0.223921,0.158998,0.153821,0.185864,-0.041768,0.035408,0.205421,0.068883,...,-0.009645,NaN,NaN,NaN,0.007118,0.058934,0.003819,0.062969,0.022607,-0.083909
A3_Score,0.074096,0.223921,1.000000,0.412722,0.264927,0.268846,0.078216,0.017771,0.315113,0.168454,...,0.055320,NaN,NaN,NaN,0.006466,-0.009742,-0.076252,0.104950,0.092765,-0.120604
A4_Score,0.127814,0.158998,0.412722,1.000000,0.306806,0.295152,0.151236,0.008617,0.327673,0.210968,...,0.023071,NaN,NaN,NaN,0.000644,0.017637,0.002357,0.016272,0.085813,-0.125520
A5_Score,0.169369,0.153821,0.264927,0.306806,1.000000,0.392354,0.238589,0.102086,0.396582,0.267561,...,0.000374,NaN,NaN,NaN,-0.037582,-0.050505,-0.032395,0.044190,0.121609,-0.136075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
relation_Others,-0.022944,0.058934,-0.009742,0.017637,-0.050505,0.021737,-0.037320,-0.008710,0.013761,0.004470,...,-0.011137,NaN,NaN,NaN,-0.006393,1.000000,-0.023385,-0.017213,-0.143234,-0.033404
relation_Parent,-0.000981,0.003819,-0.076252,0.002357,-0.032395,0.046541,-0.021089,-0.040063,0.033170,0.003431,...,0.006311,NaN,NaN,NaN,-0.020901,-0.023385,1.000000,-0.056273,-0.468269,-0.109207
relation_Relative,-0.003317,0.062969,0.104950,0.016272,0.044190,0.097436,-0.024955,-0.017913,0.045539,-0.030399,...,0.029353,NaN,NaN,NaN,-0.015385,-0.017213,-0.056273,1.000000,-0.344671,-0.080382
relation_Self,0.089246,0.022607,0.092765,0.085813,0.121609,0.019457,0.072402,0.102958,0.027339,0.114440,...,-0.022501,NaN,NaN,NaN,-0.128021,-0.143234,-0.468269,-0.344671,1.000000,-0.668887
relation_nan,-0.107144,-0.083909,-0.120604,-0.125520,-0.136075,-0.128958,-0.056257,-0.084232,-0.095659,-0.122048,...,0.012227,NaN,NaN,NaN,-0.029856,-0.033404,-0.109207,-0.080382,-0.668887,1.000000

In [ ]:
df_dummy = df_dummy.dropna()

In [ ]:
df_dummy = df_dummy[df['age'] < 200]

<ipython-input-16-cfd0276d26f4>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_dummy = df_dummy[df['age'] < 200]

In [ ]:
df_dummy.describe()

,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,...,used_app_before_yes,used_app_before_nan,age_desc_'18 and more',age_desc_nan,relation_'Health care professional',relation_Others,relation_Parent,relation_Relative,relation_Self,relation_nan
count,701.000000,701.000000,701.000000,701.000000,701.000000,701.000000,701.000000,701.000000,701.000000,701.000000,...,701.000000,701.0,701.0,701.0,701.000000,701.000000,701.000000,701.000000,701.000000,701.000000
mean,0.723252,0.453638,0.459344,0.497860,0.499287,0.285307,0.417974,0.651926,0.325250,0.574893,...,0.017118,0.0,1.0,0.0,0.005706,0.007133,0.071327,0.039943,0.743224,0.132668
std,0.447710,0.498201,0.498700,0.500352,0.500357,0.451883,0.493578,0.476700,0.468803,0.494712,...,0.129805,0.0,0.0,0.0,0.075377,0.084213,0.257554,0.195965,0.437167,0.339457
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,0.0,1.0,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df_dummy.columns

Index(['A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score', 'A6_Score',
       'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score',
       ...
       'used_app_before_yes', 'used_app_before_nan', 'age_desc_'18 and more'',
       'age_desc_nan', 'relation_'Health care professional'',
       'relation_Others', 'relation_Parent', 'relation_Relative',
       'relation_Self', 'relation_nan'],
      dtype='object', length=111)

In [ ]:
[col for col in df_dummy.columns if 'aus' in col]

['austim_no', 'austim_yes', 'austim_nan']

In [ ]:
drop_list = []  # powiązane z targetem (np 1-target, log(targetu)), nie będą dostępne kiedy będę korzystał z modelu, dane które nie będą aktulane, zrobienie korelacja z target i analiza > 0.95

In [ ]:
X, y = df_dummy.drop(columns=['austim_yes', 'austim_no', 'austim_nan']), df_dummy['austim_yes']  # tutaj był błąd

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=402, train_size=0.7)

In [ ]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [ ]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
X_test.shape

(211, 108)

In [ ]:
y_test.mean(), y_train.mean()

(0.12796208530805686, 0.1306122448979592)

In [ ]:
from sklearn import tree
clf_tree = tree.DecisionTreeClassifier(max_depth=14)  #  max_depth to jest przykład hiper parametru
clf_tree.fit(X_train, y_train)
clf_tree.score(X_test, y_test), clf_tree.score(X_train, y_train)
print(classification_report(y_test, clf_tree.predict(X_test)))

              precision    recall  f1-score   support

           0       0.89      0.85      0.87       184
           1       0.23      0.30      0.26        27

    accuracy                           0.78       211
   macro avg       0.56      0.57      0.57       211
weighted avg       0.81      0.78      0.79       211

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf = LogisticRegression(random_state=462, C=1 )
clf.fit(X_train, y_train)
clf.score(X_test, y_test), clf.score(X_train, y_train)
print(classification_report(y_test, clf.predict(X_test)))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91       184
           1       0.17      0.07      0.10        27

    accuracy                           0.83       211
   macro avg       0.52      0.51      0.51       211
weighted avg       0.78      0.83      0.81       211

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
print(classification_report(y_train, clf.predict(X_train)))

              precision    recall  f1-score   support

           0       0.91      0.98      0.95       426
           1       0.77      0.36      0.49        64

    accuracy                           0.90       490
   macro avg       0.84      0.67      0.72       490
weighted avg       0.89      0.90      0.89       490